"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { atsTips } from "@/lib/ats-tips"
import { InfoIcon, CheckCircle2 } from "lucide-react"

export function AtsTipsModal() {
  const [open, setOpen] = useState(false)

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <InfoIcon className="h-4 w-4" />
          ATS Compatibility Guide
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-xl">ATS Compatibility Guide</DialogTitle>
          <DialogDescription>
            Follow these tips to ensure your resume passes through Applicant Tracking Systems successfully.
          </DialogDescription>
        </DialogHeader>

        <div className="grid gap-4 py-4">
          {atsTips.map((tip, index) => (
            <div key={index} className="border rounded-lg p-4 bg-muted/50 hover:bg-muted transition-colors">
              <div className="flex gap-3">
                <CheckCircle2 className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                <div>
                  <h3 className="font-medium text-primary mb-1">{tip.title}</h3>
                  <p className="text-sm text-muted-foreground">{tip.description}</p>
                </div>
              </div>
            </div>
          ))}

          <div className="mt-4 p-4 border rounded-lg bg-amber-50 border-amber-200">
            <h3 className="font-medium text-amber-800 mb-1">Why ATS Compatibility Matters</h3>
            <p className="text-sm text-amber-700">
              Over 75% of resumes are rejected by ATS systems before a human ever sees them. Following these guidelines
              significantly increases your chances of getting past the initial automated screening.
            </p>
          </div>

          <div className="mt-2 p-4 border rounded-lg bg-green-50 border-green-200">
            <h3 className="font-medium text-green-800 mb-1">Our ATS-Friendly Guarantee</h3>
            <p className="text-sm text-green-700">
              All resume formats generated by this tool are specifically designed to be ATS-friendly. We use semantic
              HTML, proper heading structures, and text-based content that ATS systems can easily parse and index.
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}

